version: "3.8"
networks:
  app-tier:
    driver: bridge
services:
    oxidize:
        container_name: oxidize
        image: oxidize
        build: .
        ports:
            - "${default_port}:${default_port}"
        expose:
            - ${default_port}
        depends_on:
            - mongodb

    mongodb:
        image: 'mongo'
        restart: always
        ports:
            - "27017-27019:27017-27019"
        expose:
            - 27017-27019
        environment:
            - MONGO_INITDB_DATABASE=${mongodb_database_name}
            - MONGO_INITDB_ROOT_USERNAME=${mongodb_root_username}
            - MONGO_INITDB_ROOT_PASSWORD=${mongodb_root_pwd}
            - MONGO_TEST_USER=${mongo_test_user}
            - MONGO_TEST_PASSWORD=${mongo_test_password}
        networks:
            - app-tier 
        volumes:
            # - ./mongo-volume:/data/db
            - ./ops/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro