name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Dotenv Action
      uses: falti/dotenv-action@v1.1.3  
    - name: Copy .env file
      run: cp .env .env.dist
    - name: Launch Docker Compose
      run: docker compose up -d
    - name: Run tests
      run: cargo test --verbose
