name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Create Env File
      run: echo "${{ secrets.WEBSITE_ENV_STAGE }}" > .env
    - name: Build
      run: cargo build --verbose
    - name: Launch Docker Compose
      run: docker compose up -d
    - name: Run tests
      run: cargo test --verbose
