name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    build-and-test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Copy .env.dist to .env
          run: |
            cp .env.dist .env 
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Docker compose up
          run: docker compose up -d
        
        - name: Wait for services to be ready
          run: sleep 15
      
      - name: Run backend tests
        run: |
          docker compose exec backend sh -c "cargo test"

   
